version: "3.9"

services:
  db_not_ser:
    image: mongo:latest
    ports:
      - 17017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./storage/DBNotRel/conf:/etc/mongo
      - ./storage/DBNotRel/data:/var/lib/data

  db_serial:
    image: influxdb:1.8
    ports:
      - 18086:8086
    volumes:
      - ./storage/DBSerial/conf:/etc/influxdb
      - ./storage/DBSerial/data:/var/lib/influxdb

#volumes:
#  DBNotRelConf:
#    external: true
#  DBNotRelData:
#    external: true
#  DBRelConf:
#    external: true
#  DBRelData:
#    external: true
#  DBSerialConf:
#    external: true
#  DBSerialData:
#    external: true
