version: "3.8"

services:
  db_not_ser:
    container_name: db_not_ser
    image: mongo:latest
    ports:
      - 17017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./storage/DBNotRel/conf:/etc/mongo
      - ./storage/DBNotRel/data:/var/lib/data

  db_serial:
    image: influxdb:1.8
    container_name: db_ser
    ports:
      - 18086:8086
    volumes:
      - ./storage/DBSerial/conf:/etc/influxdb
      - ./storage/DBSerial/data:/var/lib/influxdb

  agent_save_data:
    container_name: srv_save
    build:
      context: ../
      dockerfile: docker/docker_image/agent_save.dockerfile
      args:
        - PORT=1883
        - HOST=mqtt_broker
    depends_on:
      - mqtt_broker

    
  agent_broadcast:
    container_name: srv_broadcast
    build:
      context: ../
      dockerfile: docker/docker_image/agent.dockerfile
      args:
        - PORT=1883
        - HOST=mqtt_broker
      commands: python3 main.py --mode cli_server --port $PORT --host $HOST
    depends_on:
      - mqtt_broker

  mqtt_broker:
    container_name: mqtt_broker
    image: eclipse-mosquitto:latest
    volumes:
      - ./storage/MQTT/config:/mosquitto/config
      - ./storage/MQTT/data:/mosquitto/data
      - ./storage/MQTT/log:/mosquitto/log
    ports:
      - 30000:1883
      - 30001:9001

